name: Backend CI
on:
  push:
    branches: [main]
    paths:
      - "Backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - name: Install dependencies and lint
        uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: pycodestyle .
