name: Backend CI
on:
  push:
    branches: [main]
    paths:
      - "Backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - name: Install dependencies
        uses: None
      - run: pip3 install -r requirements.txt
      - name: Run style checker
        uses: None
      - run: pycodestyle .
