name: Frontend CI
on:
  push:
    branches: [main]
    paths:
      - "Frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Install dependencies
        uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint
