name: Frontend CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Install dependencies
        uses: actions/checkout@v4
      - run: npm install
        working-directory: Frontend
